#!/bin/sh

CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $NF ~ /\.kts?$/ { print $NF }')"

if [ -z "$CHANGED_FILES" ]; then
    exit 0
fi;

diff=.git/unstaged-ktlint-git-hook.diff
git diff --color=never > $diff
if [ -s $diff ]; then
  git apply -R $diff
fi

./gradlew --quiet spotlessApply
gradle_command_exit_code=$?

echo "$CHANGED_FILES" | while read -r file; do
    if [ -f "$file" ]; then
        git add "$file"
    fi
done


if [ -s $diff ]; then
  git apply --ignore-whitespace $diff
fi
rm $diff
unset diff

exit $gradle_command_exit_code