swagger: '2.0'
info:
  title: lightroom-for-muzei
  description: Backend for the Lightroom for Muzei Android Application
  version: 0.1.0
schemes:
  - https
produces:
  - application/json
paths:
  /search:
    get:
      summary: Search
      operationId: search
      x-google-backend:
        address: https://us-central1-lightroom-for-muzei.cloudfunctions.net/lightroom-test-function
      security:
        - api_key: [ ]
      responses:
        '200':
          description: A successful response
          schema:
            type: string
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"