#!/bin/sh

GIT_HASH="$(git rev-parse --short HEAD)"

CONFIG_NAME="lightroom-for-muzei-$GIT_HASH"

echo "Creating API config ($CONFIG_NAME)"

gcloud api-gateway api-configs create $CONFIG_NAME \
  --api=lightroom-for-muzei \
  --openapi-spec=../lightroom-for-muzei-config.yaml \
  --backend-auth-service-account=api-gateway-invoker@lightroom-for-muzei.iam.gserviceaccount.com

echo "Updating gateway"

gcloud api-gateway gateways update lightroom-for-muzei-gateway \
  --api=lightroom-for-muzei --api-config=$CONFIG_NAME \
  --location=us-central1 --project=lightroom-for-muzei

echo "Gateway updated"