name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYTION_KEY }}

      - name: Lint
        run: ./gradlew lintDebug

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYTION_KEY }}

      - name: Decrypt secrets
        run: ./release/decrypt-secrets
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

      - name: Build
        run: ./gradlew bundleDebug

      - name: Test
        run: ./gradlew testDebugUnitTest

      - name: Remove secrets
        if: always()
        run: ./release/cleanup-secrets

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: android-build-outputs
          path: app/build/outputs

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: android-reports
          path: |
            **/build/reports/*

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: android-test-results
          path: |
            **/build/test-results/*
